{{- $total := len .Values.services -}}
{{- $i := 0 -}}
{{- range $serviceName, $config := .Values.services }}
{{- $i = add1 $i }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $serviceName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $serviceName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $serviceName }}
  template:
    metadata:
      labels:
        app: {{ $serviceName }}
    spec:
      containers:
      - name: {{ $serviceName }}
        image: "{{ if $config.image }}{{ $config.image }}{{ else }}{{ $.Values.global.registry }}/yas-{{ $serviceName }}:{{ $config.tag | default $.Values.global.defaultTag }}{{ end }}"
{{- if $config.args }}
        args:
{{ toYaml $config.args | indent 8 }}
{{- end }}
        ports:
        - containerPort: {{ $config.port }}
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgresql.dev.svc.cluster.local:5432/yas_{{ $serviceName }}"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "yas_password"
        - name: HOSTNAME
          value: "0.0.0.0"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka.dev.svc.cluster.local:9092"
{{- if ne $i $total }}
---
{{- end }}
{{- end }}