apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-realm-import
  namespace: {{ .Release.Namespace }}
data:
  yas-realm.json: |
    {
      "id": "Yas",
      "realm": "Yas",
      "enabled": true
    }
