apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/kiyoneshin/yas-manifests.git'
    targetRevision: HEAD
    path: yas-apps
    helm:
      valueFiles:
        - ../dev/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true