services:
  tax:
    tag: "main"
  product:
    tag: "main"
  cart:
    tag: "main"
  order:
    tag: "main"
  customer:
    tag: "main"
  inventory:
    tag: "main"
  media:
    tag: "main"
  search:
    tag: "main"
  storefront-bff:
    tag: "main"
  backoffice-bff:
    tag: "main"
  storefront-ui:
    image: "nashtechgarage/yas-storefront-ui:latest"
  backoffice-ui:
    image: "nashtechgarage/yas-backoffice-ui:latest"
  swagger-ui:
    image: "swaggerapi/swagger-ui:latest"
